# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-vm-extension

spec:
  type: application # or service, library, etc.
  owner: group:obs-cloud-monitoring # Find your group in https://backstage.elastic.dev/catalog?filters%5Bkind%5D=group
  lifecycle: production # or production, deprecated, etc.

# Declare your Buildkite pipeline.
# This declaration creates the Backstage entity and the pipeline in Buildkite.
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-azure-vm-extension
  description: Buildkite Pipeline for azure-vm-extension
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/azure-vm-extension

spec:
  type: buildkite-pipeline
  owner: group:obs-cloud-monitoring
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: azure-vm-extension
    spec:
      repository: elastic/azure-vm-extension
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        obs-cloud-monitoring:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY