---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-azure-vm-extension
  description: 'Pipeline for Azure VM extension project'
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/azure-vm-extension

spec:
  type: buildkite-pipeline
  owner: group:azure-vm-extension-management
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: azure-vm-extension
      description: 'Pipeline for Azure VM extension project'
    spec:
      branch_configuration: "main"
      pipeline_file: ".buildkite/pipeline.yml"
      provider_settings:
        build_pull_request_forks: false
        build_pull_requests: true # requires filter_enabled and filter_condition settings as below when used with buildkite-pr-bot
        build_tags: false
        filter_enabled: true
        filter_condition: >-
          build.pull_request.id == null || (build.creator.name == 'elasticmachine' && build.pull_request.id != null)
      repository: elastic/azure-vm-extension
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
      skip_intermediate_builds: true
      skip_intermediate_builds_branch_filter: '!main'
      env:
        ELASTIC_PR_COMMENTS_ENABLED: 'true'
      teams:
        azure-vm-extension-management:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY