#!/usr/bin/env groovy
// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
@Library('apm@current') _

pipeline {
  agent { label 'ubuntu-20' }
  environment {
    REPO = "azure-vm-extension"
    NOTIFY_TO = credentials('notify-to')
    PIPELINE_LOG_LEVEL = 'INFO'
    LANG = "C.UTF-8"
    LC_ALL = "C.UTF-8"
    HOME = "${env.WORKSPACE}"
    PATH = "${env.HOME}/bin:${env.PATH}"
    CLUSTER_NAME = "test-azure-${BUILD_ID}-${BRANCH_NAME}"
    ELASTIC_STACK_VERSION = '7.12.1'   // This should be a matrix
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5', daysToKeepStr: '7'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    timeout(time: 2, unit: 'HOURS')
    disableConcurrentBuilds()
  }
  stages {
    stage('Checkout'){
      steps {
        deleteDir()
        checkout scm
      }
    }
    stage('Create cluster'){
      steps {
        withVaultEnv(){
          sh(label: 'Deploy Cluster', script: 'make -C .ci create-cluster')
        }
      }
    }
    stage('Prepare tools') {
      steps {
        withCloudEnv() {
          sh(label: 'Prepare tools', script: 'make -C .ci prepare-tool')
        }
      }
      post {
        failure {
          destroyCluster()
        }
      }
    }
    stage('Terraform') {
      steps {
        withCloudEnv() {
          sh(label: 'Run Terraform', script: 'make -C .ci run-terraform')
        }
      }
      post {
        failure {
          destroyTerraform()
          destroyCluster()
        }
      }
    }
    stage('Validate') {
      steps {
        withCloudEnv() {
          sh(label: 'Validate', script: 'make -C .ci validate')
        }
      }
      post {
        failure {
          withCloudEnv() {
            destroyTerraform()
          }
          destroyCluster()
        }
      }
    }
    stage('Destroy cluster'){
      steps {
        withCloudEnv() {
          destroyTerraform()
        }
        destroyCluster()
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
  }
}

def destroyCluster( ) {
  withVaultEnv(){
    sh(label: 'Destroy Cluster', script: 'make -C .ci destroy-cluster')
  }
}

def destroyTerraform( ) {
  sh(label: "Run Terraform", script: 'make -C .ci destroy-terraform')
}

def withVaultEnv(Closure body){
  getVaultSecret.readSecretWrapper {
    withEnvMask(vars: [
      [var: 'VAULT_ADDR', password: env.VAULT_ADDR],
      [var: 'VAULT_ROLE_ID', password: env.VAULT_ROLE_ID],
      [var: 'VAULT_SECRET_ID', password: env.VAULT_SECRET_ID],
      [var: 'VAULT_AUTH_METHOD', password: 'approle'],
      [var: 'VAULT_AUTHTYPE', password: 'approle']
    ]){
      body()
    }
  }
}

def withCloudEnv(Closure body) {
  def props = getVaultSecret(secret: "secret/observability-team/ci/test-clusters/${env.CLUSTER_NAME}/ec-deployment")
  if (props?.errors) {
    error "withCloudEnv: Unable to get credentials from the vault: ${props.errors.toString()}"
  }
  if (props?.data?.cloud_id?.trim() || props?.data?.username?.trim() || props?.data?.password?.trim()) {
    error "withCloudEnv: Missing data in the credentials"
  }
  withEnvMask(vars: [
    [var: 'TF_VAR_username', password: props?.data?.password],
    [var: 'TF_VAR_password', password: props?.data?.username],
    [var: 'TF_VAR_cloudId', password: props?.data?.cloud_id]
  ]){
    body()
  }
}
